### ISSUE TITLE
Suggestion: Include the conversion of 'nil' to :false or :true

### ISSUE THREAD

**Issue by lflucasferreira** [piotrmurach/necromancer#5]
It's only an idea that came up.

I need always to check if something is true, but if it is nil, then is false.

In that case, I don't know (didn't try) how to solve this problem using Necromancer.

**Comment by piotrmurach** [comment]
Hi Lucas,

Thanks for checking out this library.

What you want, if I understand correctly, is a check that is outside of the scope of this library. This library aim is to help with converting one data type into another. It's fairly deterministic in what it does.

However, you can create you own [custom converter](https://github.com/piotrmurach/necromancer#37-custom) that changes `nil` into `false` or `true` value.

Unfortunately, I don't see utility in your suggestion and hence I won't be adding it here.
